language: python
jdk:
  - openjdk7
  - oraclejdk7
env:
  - DIR=Collections
  - DIR=JpaTutorial
  - DIR=EJBdeploy
  - DIR=EyeCare
  - DIR=TextPad
  - DIR=WEBdeploy
  - DIR=filedesc
  - DIR=FileSync
  - DIR=TextToVoice
  - DIR=JavaReflect
  - DIR=PDFgen
  - DIR=Terminal
  - DIR=ArithmeticParser
  - DIR=StudentsHibernate
  - DIR=jssh
script: python run.py $DIR
