#!/bin/bash

ant jar
mkdir -p /opt/sw/terminal/
cp bin/jar/Terminal.jar  /opt/sw/terminal/
cp terminal /usr/local/bin/
cp terminal.desktop /usr/share/applications/
cp src/org/sumanta/resources/terminal.gif /opt/sw/terminal/terminal.gif
chmod +x /usr/local/bin/terminal

