#!/bin/bash

ant jar
mkdir -p /opt/sw/terminal/
cp bin/jar/Terminal.jar  /opt/sw/terminal/
cp terminal /usr/local/bin/
cp terminal.desktop /usr/share/applications/
cp xterm.xpm /opt/sw/terminal/xterm.xpm
chmod +x /usr/local/bin/terminal
ant clean
